### ISSUE TITLE
Feature Request: Show only current user's adopted hydrants

### ISSUE THREAD

**Issue by skandl** [codeforamerica/adopt-a-hydrant#58]
It would be nice to have an ability to show only the hydrants adopted by the current user, since in a city of any reasonable size it's easy for the user's hydrants to become lost among all the others.

**Comment by thefenry** [comment]
Did you have any ideas as to what you want it to look like? Maybe a button on the top right of the map? Perhaps on the sidebar?

**Comment by codeman869** [comment]
Created a pull [#78](https://github.com/codeforamerica/adopt-a-hydrant/pull/78)
