### ISSUE TITLE
git clone command listed in README

### ISSUE THREAD

**Issue by blurredbits** [codeforamerica/adopt-a-hydrant#61]
Used: 

     git clone git@github.com:codeforamerica/adopt-a-hydrant.git

Vs.

     git clone git://github.com/codeforamerica/adopt-a-hydrant.git

as listed in the readme. Command listed kept giving a:

     fatal: unable to connect to github.com:
     errno=Operation timed out

**Comment by amZotti** [comment]
The version of the command specified in the README worked for me. Something is probably off in your Git configurations somewhere.

**Comment by gabriellhrn** [comment]
This issue is not updated for a long time. Also both commands worked for me. Could not this issue be closed?
