### ISSUE TITLE
No resources being loaded

### ISSUE THREAD

**Issue by rghamilton3** [codeforamerica/adopt-a-hydrant#66]
It seems that no resources can be sourced and all are responding with 404 errors.

![screen shot 2015-04-25 at 5 21 13 pm](https://cloud.githubusercontent.com/assets/2868423/7335136/de778fec-eb6f-11e4-8961-fecd1ac785ca.png)

**Comment by sferik** [comment]
Thanks for reporting this. The problem should be fixed now.
