### ISSUE TITLE
More Hydrants on map by default 

### ISSUE THREAD

**Issue by CostantinB** [codeforamerica/adopt-a-hydrant#69]
I would like to show more Hydrants on the map on my homepage. Now it shows 10 hydrants and as you zoom/change area more drop in. Where can I edit this? Thanks

**Comment by sferik** [comment]
The `Thing#find_closest` method take as limit argument that defaults to 10. https://github.com/codeforamerica/adopt-a-hydrant/blob/master/app/models/thing.rb#L15

**Comment by CostantinB** [comment]
Hey, sorry to bother you again. I’ve changed the relative line as you suggested but nothing changes. Any suggestions? 
http://adoptahydrant.xyz
https://github.com/CostantinB/adopt-a-hydrant/blob/master/app/models/thing.rb#L15

**Comment by CostantinB** [comment]
The solution is actually to change 
https://github.com/codeforamerica/adopt-a-hydrant/blob/master/app/controllers/things_controller.rb#L5
